; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Mon Mar 14 2022 19:56:59 GMT+0100 (heure normale d’Europe centrale)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


