; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Mon Mar 14 2022 19:57:01 GMT+0100 (heure normale d’Europe centrale)
G91               ; relative positioning
G1 H1 Y780 F1800 ; move quickly to Y axis endstop and stop there (first pass)
G1 H2 Y-5 F6000    ; go back a few mm
G1 H1 Y780 F360  ; move slowly to Y axis endstop once more (second pass)
G90               ; absolute positioning

