; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Mon Mar 14 2022 19:57:02 GMT+0100 (heure normale d’Europe centrale)
G90            ; absolute positioning
G1 Z103        ; lift Z to max height
M5             ; stop spindle

G90            ; absolute positioning
G1 X0 Y771     ; go to back left



