; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Mon Mar 14 2022 19:57:02 GMT+0100 (heure normale d’Europe centrale)
G1 R1 X0 Y0 Z5 F6000 ; go to 5mm above position of the last print move
M3                   ; start spindle
G1 R1 X0 Y0 Z0       ; go back to the last print move

